config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im-oaipmh-client:
      branch: main
      repo: https://github.com/grycap/im-oaipmh-client
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im-oaipmh-client git:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-celadon-bonobo.sh
        container: qc.acc_nippy-heliotrope-millipede
  QC.Doc:
    repos:
      github.com/grycap/im-oaipmh-client find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-amber-whippet.sh
        container: qc.doc_muzzy-lavender-robin
      github.com/grycap/im-oaipmh-client git:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-violet-setter.sh
        container: qc.doc_woolly-goldenrod-squid
      github.com/grycap/im-oaipmh-client markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-coral-leopard.sh
        container: qc.doc_squeaky-chestnut-jellyfish
  QC.Lic:
    repos:
      github.com/grycap/im-oaipmh-client licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-tomato-eagle.sh
        container: qc.lic_tasty-plum-zorse
  QC.Met:
    repos:
      github.com/grycap/im-oaipmh-client validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.homey-chestnut-weasel.sh
        container: qc.met_goopy-apricot-fox
  QC.Sec:
    repos:
      github.com/grycap/im-oaipmh-client bandit:
        commands:
        - /usr/bin/env sh .sqa/script.randy-flax-spitz.sh
        container: qc.sec_smelly-russet-impala
  QC.Sty:
    repos:
      github.com/grycap/im-oaipmh-client flake8:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-rose-chamois.sh
        container: qc.sty_frumpy-green-shrew
      github.com/grycap/im-oaipmh-client jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-malachite-husky.sh
        container: qc.sty_woozy-firebrick-gorilla
  QC.Uni:
    repos:
      github.com/grycap/im-oaipmh-client pytest:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-firebrick-squid.sh
        container: qc.uni_chummy-celadon-bear
  QC.Ver:
    repos:
      github.com/grycap/im-oaipmh-client get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-vermilion-armadillo.sh
        container: qc.ver_snappy-crimson-turtle
timeout: 5400
