config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im-oaipmh-client:
      branch: main
      repo: https://github.com/grycap/im-oaipmh-client
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im-oaipmh-client git:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-taupe-lobster.sh
        container: qc.acc_trippy-cerulean-mole
  QC.Doc:
    repos:
      github.com/grycap/im-oaipmh-client find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-zucchini-dog.sh
        container: qc.doc_thirsty-turquoise-ray
      github.com/grycap/im-oaipmh-client git:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-sapphire-gibbon.sh
        container: qc.doc_foggy-saffron-bongo
      github.com/grycap/im-oaipmh-client markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-lavender-uakari.sh
        container: qc.doc_scanty-peach-vole
  QC.Lic:
    repos:
      github.com/grycap/im-oaipmh-client licensee:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-olivine-woodpecker.sh
        container: qc.lic_skinny-silver-newfoundland
  QC.Met:
    repos:
      github.com/grycap/im-oaipmh-client validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-orange-albatross.sh
        container: qc.met_chewy-beige-coati
  QC.Sec:
    repos:
      github.com/grycap/im-oaipmh-client bandit:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-razzmatazz-dragon.sh
        container: qc.sec_messy-yellow-dolphin
  QC.Sty:
    repos:
      github.com/grycap/im-oaipmh-client flake8:
        commands:
        - /usr/bin/env sh .sqa/script.homely-maroon-moose.sh
        container: qc.sty_queasy-black-wasp
      github.com/grycap/im-oaipmh-client jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-wisteria-fox.sh
        container: qc.sty_muzzy-razzmatazz-oyster
  QC.Uni:
    repos:
      github.com/grycap/im-oaipmh-client pytest:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-saffron-quail.sh
        container: qc.uni_smelly-puce-skunk
  QC.Ver:
    repos:
      github.com/grycap/im-oaipmh-client get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.randy-crimson-dormouse.sh
        container: qc.ver_lovely-gold-chipmunk
timeout: 5400
