config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im-oaipmh-client:
      branch: main
      repo: https://github.com/grycap/im-oaipmh-client
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im-oaipmh-client git:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-cyan-earwig.sh
        container: qc.acc_muzzy-sepia-falcon
  QC.Doc:
    repos:
      github.com/grycap/im-oaipmh-client find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-cream-bonobo.sh
        container: qc.doc_chummy-purple-tarantula
      github.com/grycap/im-oaipmh-client git:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-cream-saola.sh
        container: qc.doc_leaky-xanthic-lionfish
      github.com/grycap/im-oaipmh-client markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-black-oriole.sh
        container: qc.doc_skinny-persimmon-chipmunk
  QC.Lic:
    repos:
      github.com/grycap/im-oaipmh-client licensee:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-silver-schnauzer.sh
        container: qc.lic_surly-turquoise-avocet
  QC.Met:
    repos:
      github.com/grycap/im-oaipmh-client validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-rust-gecko.sh
        container: qc.met_cloudy-corn-shark
  QC.Sec:
    repos:
      github.com/grycap/im-oaipmh-client bandit:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-viridian-chamois.sh
        container: qc.sec_baggy-chestnut-buzzard
  QC.Sty:
    repos:
      github.com/grycap/im-oaipmh-client flake8:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-lilac-buffalo.sh
        container: qc.sty_sleepy-jade-tuatara
      github.com/grycap/im-oaipmh-client jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-purple-flounder.sh
        container: qc.sty_stinky-vermilion-dragon
  QC.Uni:
    repos:
      github.com/grycap/im-oaipmh-client pytest:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-cobalt-budgerigar.sh
        container: qc.uni_frumpy-wheat-rattlesnake
  QC.Ver:
    repos:
      github.com/grycap/im-oaipmh-client get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-razzmatazz-crocodile.sh
        container: qc.ver_frumpy-ecru-cuttlefish
timeout: 5400
