config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im-oaipmh-client:
      branch: main
      repo: https://github.com/grycap/im-oaipmh-client
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im-oaipmh-client git:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-magnolia-zebra.sh
        container: qc.acc_foggy-khaki-cockroach
  QC.Doc:
    repos:
      github.com/grycap/im-oaipmh-client find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-indigo-squirt.sh
        container: qc.doc_homely-copper-lemming
      github.com/grycap/im-oaipmh-client git:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-dandelion-dodo.sh
        container: qc.doc_scanty-persimmon-okapi
      github.com/grycap/im-oaipmh-client markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-lavender-goat.sh
        container: qc.doc_woolly-scarlet-balinese
  QC.Lic:
    repos:
      github.com/grycap/im-oaipmh-client licensee:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-coral-dhole.sh
        container: qc.lic_breezy-puce-reindeer
  QC.Met:
    repos:
      github.com/grycap/im-oaipmh-client validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-cerise-crane.sh
        container: qc.met_blurry-yellow-octopus
  QC.Sec:
    repos:
      github.com/grycap/im-oaipmh-client bandit:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-tan-quokka.sh
        container: qc.sec_ugly-gold-hyena
  QC.Sty:
    repos:
      github.com/grycap/im-oaipmh-client flake8:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-ruby-fowl.sh
        container: qc.sty_skanky-plum-mastiff
      github.com/grycap/im-oaipmh-client jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-wheat-neanderthal.sh
        container: qc.sty_flabby-charcoal-wolfhound
  QC.Uni:
    repos:
      github.com/grycap/im-oaipmh-client pytest:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-aquamarine-lion.sh
        container: qc.uni_snippy-firebrick-grouse
  QC.Ver:
    repos:
      github.com/grycap/im-oaipmh-client get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-amaranth-tamarin.sh
        container: qc.ver_skimpy-ochre-havanese
timeout: 5400
