config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im-oaipmh-client:
      branch: main
      repo: https://github.com/grycap/im-oaipmh-client
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im-oaipmh-client git:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-pink-wallaby.sh
        container: qc.acc_dorky-periwinkle-panda
  QC.Doc:
    repos:
      github.com/grycap/im-oaipmh-client find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-rust-kingfisher.sh
        container: qc.doc_squirrely-chartreuse-gharial
      github.com/grycap/im-oaipmh-client git:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-tan-magpie.sh
        container: qc.doc_silly-green-tuatara
      github.com/grycap/im-oaipmh-client markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-ochre-pinscher.sh
        container: qc.doc_cloudy-orchid-eagle
  QC.Lic:
    repos:
      github.com/grycap/im-oaipmh-client licensee:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-plum-fowl.sh
        container: qc.lic_sickly-orchid-havanese
  QC.Met:
    repos:
      github.com/grycap/im-oaipmh-client validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-saffron-whale.sh
        container: qc.met_snoopy-aqua-giraffe
  QC.Sec:
    repos:
      github.com/grycap/im-oaipmh-client bandit:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-bistre-frigatebird.sh
        container: qc.sec_beady-khaki-panda
  QC.Sty:
    repos:
      github.com/grycap/im-oaipmh-client flake8:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-green-greyhound.sh
        container: qc.sty_smelly-plum-flounder
      github.com/grycap/im-oaipmh-client jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-maroon-monkey.sh
        container: qc.sty_bluesy-jade-seal
  QC.Uni:
    repos:
      github.com/grycap/im-oaipmh-client pytest:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-wheat-gar.sh
        container: qc.uni_stuffy-razzmatazz-woodpecker
  QC.Ver:
    repos:
      github.com/grycap/im-oaipmh-client get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-cerise-wombat.sh
        container: qc.ver_cozy-peach-chimpanzee
timeout: 5400
